### ISSUE TITLE
[Error 404: NOT FOUND] Deployment cannot be found 

### ISSUE THREAD

**Issue by shubhansu-kr** [Himasnhu-AT/adminNexus#12]
The link in the description [https://admin-nexus-eight.vercel.app/](https://admin-nexus-eight.vercel.app/), is not live. Lead to a broken page with the following error: 
![image](https://github.com/user-attachments/assets/c42d07bc-bca1-42af-baf8-3ca89bd3144e)

We need to fix this deployment link.

**Comment by Himasnhu-AT** [comment]
@shubhansu-kr 
Hey thanks for pointing it out. 
i changed the deployment link and it didn't got updated here. will do that
